### PR TITLE
Done with ticket #9: view all categories

### PR DESCRIPTION
**Pull request by GloriaReina**
# Description
The functionality to view a list of categories has been added. Given a user is logged in the app & selects the Category Management link in the navbar, they should be directed to an  'Index' view page that lists all the Category names in alphabetical order. 

# Additional Information
Users will see hyperlink options to edit, delete, or see details of a category. At this time, these features are not yet built
                -For the time being  all users are admin users. 

# Type of change:
*New feature (non-breaking change which adds functionality)

# Testing Instructions:
1. git add and git commit whatever you're working on on your branch
2. git checkout main
3. git fetch --a
4. git checkout  grTicket9
5. If you don't see the most recent version of my files, git pull origin grTicket9
6. Make sure to add all seed data before testing
7. ctrl + a and delete what is in your query and replace it with this to seed the database
8. Use this to fill out tables and columns:
              https://github.com/NewForce-Cohort-7/tabloidmvc-mollasses- 
              gang/blob/main/SQL/01_TabloidMVC_Create_DB.sql
9. Use this to seed the database: 
               https://github.com/NewForce-Cohort-7/tabloidmvc-mollasses- 
              gang/blob/main/SQL/02_TabloidMVC_Seed_Data.sql
11. Click the execute solid green button to create database
12. Click the execute with debugger solid green button to launch the app
13. In browser, go to Login on the nav bar
14. Log in with this email: admin@example.com. This should direct you to the home page.
15. In the homepage, select the Category Management link in the navbar: Will directed you to a lists all the Categories
16. You will see two columns(properties) called Id & Name. In the Name column, besides the category name, you will see 3 links [Edit, Details, and Delete]. At present there are 13 categories, and so 13 rows.
17. Log out should be showing on the nav bar now. Please click this to log out.

# Checklist:

- [x ] - My code follows the style guidelines of this project
- [x ] -  I have performed a self-review of my code
- [x ] - I have commented my code, particularly in hard-to-understand areas
- [x ] -  My changes generate no new warnings or errors
- [x ] - I have added test instructions that prove that my feature works

### CODE REVIEW

**Comment by Tommy-Spurlock** [comment]
Looks great but needs a few adjustments. 
 - on step 4 go ahead and name the branch that we want to use.
 - a more detailed approach on how to create the database is needed. 
 - exactly what should the user see in the category list? how many should there be? what properties do they have?

**Comment by Tommy-Spurlock** [comment]
Amazing. however the sqlserver will be different for each machine. so you don't need the "Rush-EJ95JHO3GT\  portion

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
We do not need to create a brand new project to create a DB or to test out this pull request. We would have cloned it down to be able to access it. So you wouldn't need for step 6 1-6 and then you also wouldn't necessarily need 7-9 - "Please right click on your local SQL express server and select new query" then instead of 11 you could just "ctrl + a and delete what is in your query and replace it with this to seed the database" 

https://github.com/NewForce-Cohort-5/tabloidmvc-the-runtime-terrors/pull/7

**Review by sarahebrooks12 — APPROVED** [review]
- Looks great 👼

**Pull request merged**
